/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Clases.Consultas;
import Clases.Modificaciones;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author Javier
 */
public class VentanaEliminarStaff extends javax.swing.JFrame {
    public Modificaciones modificacion;
    public Consultas consulta;
    public ResultSet rs;
    public String updateSQL;
    
    public void setModificacion(Modificaciones modificacion) {
        this.modificacion = modificacion;
    }
    public void setConsulta(Consultas consulta) {
        this.consulta = consulta;
    }
    public JComboBox<String> getVerTours() {
        return verTours;
    }
    public JComboBox<String> getVerGuias() {
        return verGuias;
    }
    /**
     * Creates new form VentanaEliminarStuff
     */
    public VentanaEliminarStaff() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        tituloElegirTour = new javax.swing.JLabel();
        verTours = new javax.swing.JComboBox<>();
        seleccionarTour = new javax.swing.JButton();
        verGuias = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        eliminarGuiaDeUnTour = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel4.setText("Menú para eliminar Guías de un Staff de Tour");

        tituloElegirTour.setText("Por favor, seleccione el Tour:");

        seleccionarTour.setText("Seleccionar");
        seleccionarTour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccionarTourActionPerformed(evt);
            }
        });

        jLabel2.setText("Por favor, seleccione el Guía a eliminar:");

        eliminarGuiaDeUnTour.setText("Eliminar");
        eliminarGuiaDeUnTour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarGuiaDeUnTourActionPerformed(evt);
            }
        });
        eliminarGuiaDeUnTour.setVisible(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel4)
                .addContainerGap(66, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(eliminarGuiaDeUnTour)
                    .addComponent(seleccionarTour)
                    .addComponent(tituloElegirTour)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(verGuias, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(verTours, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(110, 110, 110))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel4)
                .addGap(30, 30, 30)
                .addComponent(tituloElegirTour)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(verTours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(seleccionarTour)
                .addGap(55, 55, 55)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(verGuias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(eliminarGuiaDeUnTour)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void seleccionarTourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionarTourActionPerformed
        try {
            int n = verTours.getSelectedItem().toString().length();
            
            String IDt = verTours.getSelectedItem().toString().substring(n-1, n);
            if(Character.isDigit(verTours.getSelectedItem().toString().charAt(n-2))){
                IDt = verTours.getSelectedItem().toString().substring(n-2, n);
            }
            
            //Consulta para llenar combobox con Nombre y Código de los(as) Guías.
            String consultaStaffTourSQL = "SELECT G.nombre_completo, G.RUT_guía "
                    + "FROM Guía G, Dirigen D "
                    + "WHERE G.RUT_guía = D.RUT_guía AND D.código_tour = " + IDt;
            
            rs = consulta.hacerConsulta(consultaStaffTourSQL);
            while(rs.next()){
                getVerGuias().addItem(rs.getString("nombre_completo") + ", con RUT: " + rs.getString("RUT_guía"));
            }
            
            if(getVerGuias().getItemCount() == 0){
                JOptionPane.showMessageDialog(null, "No hay Guías en el Tour especificado.");
                this.setVisible(false);
            }
                
            tituloElegirTour.setText(verTours.getSelectedItem().toString());
            verTours.setVisible(false);
            seleccionarTour.setVisible(false);
            eliminarGuiaDeUnTour.setVisible(true);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error al agregar." + ex.getMessage());
        }
    }//GEN-LAST:event_seleccionarTourActionPerformed

    private void eliminarGuiaDeUnTourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarGuiaDeUnTourActionPerformed
        int n = verGuias.getSelectedItem().toString().length();
        
        //seleccionar RUT desde el combobox (RUT al final)
        String RUT = verGuias.getSelectedItem().toString().substring(n-11, n);
        if(Character.isDigit(verGuias.getSelectedItem().toString().charAt(n-12))){
            RUT = verGuias.getSelectedItem().toString().substring(n-12, n);
        }

        updateSQL = "DELETE FROM Dirigen "
        + "WHERE RUT_guía = '"+ RUT +"'";

        modificacion.hacerModificacion(updateSQL);
        eliminarGuiaDeUnTour.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_eliminarGuiaDeUnTourActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaEliminarStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaEliminarStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaEliminarStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaEliminarStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaEliminarStaff().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton eliminarGuiaDeUnTour;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton seleccionarTour;
    private javax.swing.JLabel tituloElegirTour;
    private javax.swing.JComboBox<String> verGuias;
    private javax.swing.JComboBox<String> verTours;
    // End of variables declaration//GEN-END:variables
}
