/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Clases.Consultas;
import Clases.Modificaciones;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author Javier
 */
public class VentanaEliminarTuristasDeTours extends javax.swing.JFrame {
    public Modificaciones modificacion;
    public Consultas consulta;
    public ResultSet rs;
    
    public void setModificacion(Modificaciones modificacion) {
        this.modificacion = modificacion;
    }
    public void setConsulta(Consultas consulta) {
        this.consulta = consulta;
    }
    public JComboBox<String> getVerTours() {
        return verTours;
    }
    public JComboBox<String> getVerTuristas() {
        return verTuristas;
    }
    /**
     * Creates new form VentanaEliminarTuristasDeTours
     */
    public VentanaEliminarTuristasDeTours() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        verTuristas = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        tituloElegirTour = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        seleccionarTour = new javax.swing.JToggleButton();
        verTours = new javax.swing.JComboBox<>();
        eliminarTuristaTour = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel4.setText("Eliminar Turista a una Jornada de Tour");

        tituloElegirTour.setText("Por favor, seleccione el Tour:");

        jLabel2.setText("Elija el Turista a eliminar de la Jornada de Tour:");

        seleccionarTour.setText("Seleccionar");
        seleccionarTour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccionarTourActionPerformed(evt);
            }
        });

        eliminarTuristaTour.setText("Eliminar Turista del Tour");
        eliminarTuristaTour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarTuristaTourActionPerformed(evt);
            }
        });
        eliminarTuristaTour.setVisible(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(eliminarTuristaTour)
                    .addComponent(seleccionarTour)
                    .addComponent(tituloElegirTour)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addComponent(verTuristas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(verTours, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel4)
                .addGap(30, 30, 30)
                .addComponent(tituloElegirTour)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(verTours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(seleccionarTour)
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(verTuristas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(eliminarTuristaTour)
                .addContainerGap(128, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void seleccionarTourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionarTourActionPerformed
        try {
            int n = verTours.getSelectedItem().toString().length();
            
            String IDt = verTours.getSelectedItem().toString().substring(n-1, n);
            if(Character.isDigit(verTours.getSelectedItem().toString().charAt(n-2))){
                IDt = verTours.getSelectedItem().toString().substring(n-2, n);
            }
            
            //Consulta para llenar combobox con Nombre y Código de los(as) Guías.
            String consultaJornadaSQL = "SELECT T.nombre_turista, T.RUT_turista "
                    + "FROM Turistas T, Jornada J, Tour H "
                    + "WHERE T.RUT_turista = J.RUT_turista AND H.código_tour = J.código_tour AND J.código_tour = " + IDt;
            
            rs = consulta.hacerConsulta(consultaJornadaSQL);
            while(rs.next()){
                getVerTuristas().addItem(rs.getString("nombre_turista") + ", con RUT: " + rs.getString("RUT_turista"));
            }
            
            if(getVerTuristas().getItemCount() == 0){
                JOptionPane.showMessageDialog(null, "No hay Turistas en el Tour especificado.");
                this.setVisible(false);
            }
                
            tituloElegirTour.setText(verTours.getSelectedItem().toString());
            verTours.setVisible(false);
            seleccionarTour.setVisible(false);
            eliminarTuristaTour.setVisible(true);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error al agregar." + ex.getMessage());
        }
    }//GEN-LAST:event_seleccionarTourActionPerformed

    private void eliminarTuristaTourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarTuristaTourActionPerformed
        int n = verTuristas.getSelectedItem().toString().length();
        
        //seleccionar RUT desde el combobox (RUT al final)
        String RUT = verTuristas.getSelectedItem().toString().substring(n-11, n);
        if(Character.isDigit(verTuristas.getSelectedItem().toString().charAt(n-12))){
            RUT = verTuristas.getSelectedItem().toString().substring(n-12, n);
        }

        String updateSQL = "DELETE FROM Jornada "
        + "WHERE RUT_turista = '"+ RUT +"'";

        modificacion.hacerModificacion(updateSQL);
        
        this.setVisible(false);
    }//GEN-LAST:event_eliminarTuristaTourActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaEliminarTuristasDeTours.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaEliminarTuristasDeTours.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaEliminarTuristasDeTours.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaEliminarTuristasDeTours.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaEliminarTuristasDeTours().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton eliminarTuristaTour;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JToggleButton seleccionarTour;
    private javax.swing.JLabel tituloElegirTour;
    private javax.swing.JComboBox<String> verTours;
    private javax.swing.JComboBox<String> verTuristas;
    // End of variables declaration//GEN-END:variables
}
