/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Clases.Consultas;
import Clases.Modificaciones;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author Javier
 */
public class VentanaAgregarTour extends javax.swing.JFrame {
    public Modificaciones modificacion;
    //Nótese que Modificaciones enlaza con la BD, por lo que no se requiere instancia de clases PostgreSQL ni Connection
    public Consultas consulta;
    
    public ResultSet rs;
    public String updateSQL;

    public void setModificacion(Modificaciones modificacion) {
        this.modificacion = modificacion;
    }

    public void setConsulta(Consultas consulta) {
        this.consulta = consulta;
    }
    public JComboBox<String> getVerCiudades() {
        return verCiudades;
    }
    /**
     * Creates new form EliminarTours
     */
    public VentanaAgregarTour() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nombreTour = new javax.swing.JTextField();
        minimoGrupal = new javax.swing.JTextField();
        costoIndiv = new javax.swing.JTextField();
        costoGrupal = new javax.swing.JTextField();
        agregarTour = new javax.swing.JButton();
        verCiudades = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        asociarLugar = new javax.swing.JToggleButton();
        agregarCiudad = new javax.swing.JToggleButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel4.setText("Menu para agregar un Tour");

        jLabel1.setText("Nombre del tour:");

        jLabel2.setText("Mínimo de personas (Grupal):");

        jLabel3.setText("Costo individual:");

        jLabel5.setText("Costo grupal:");

        agregarTour.setText("Agregar Tour");
        agregarTour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarTourActionPerformed(evt);
            }
        });

        jLabel6.setText("Ciudad:");

        asociarLugar.setText("Asociar nuevo Lugar a un Tour");
        asociarLugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asociarLugarActionPerformed(evt);
            }
        });

        agregarCiudad.setText("Agregar nueva Ciudad");
        agregarCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarCiudadActionPerformed(evt);
            }
        });

        jLabel7.setText("Si desea asociar un Lugar a un Tour, click en el botón:");

        jLabel8.setText("Si no encuentra la ciudad que busca, puede agregarla aquí:");

        jLabel9.setText("Presione el botón para agregar el Tour:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(agregarTour, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(costoGrupal, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(verCiudades, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nombreTour)
                                .addComponent(minimoGrupal)
                                .addComponent(costoIndiv, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(asociarLugar)
                            .addComponent(agregarCiudad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel4)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(nombreTour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(minimoGrupal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(costoIndiv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(costoGrupal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(verCiudades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agregarTour)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(asociarLugar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agregarCiudad)
                    .addComponent(jLabel8))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarTourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarTourActionPerformed
        int n = verCiudades.getSelectedItem().toString().length();
        String IDc = verCiudades.getSelectedItem().toString().substring(n-1, n);
        
        if(Character.isDigit(verCiudades.getSelectedItem().toString().charAt(n-2))){
            IDc = verCiudades.getSelectedItem().toString().substring(n-2, n);
        }
        
        updateSQL = "INSERT INTO Tour(nombre_repres, mínimo_grupal, costo_indiv, costo_grupal, cod_ciudad) "
                  + "VALUES "
                  + "('"
                  + nombreTour.getText()+"', "
                  + minimoGrupal.getText() + ", "
                  + costoIndiv.getText()+", "
                  + costoGrupal.getText()+", "
                  + IDc +")";
        
        try{
            modificacion.hacerModificacion(updateSQL);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error al agregar.");
        }
    }//GEN-LAST:event_agregarTourActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_formWindowClosing

    private void asociarLugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asociarLugarActionPerformed
        try {
            VentanaAsociarLugarTour ventanaAsociarLugarTour = new VentanaAsociarLugarTour();
            ventanaAsociarLugarTour.setModificacion(modificacion);
            ventanaAsociarLugarTour.setConsulta(consulta);
            
            String consultaLugarSQL = "SELECT nombre_lugar, código_lugar "
                    + "FROM Lugar "
                    + "ORDER BY código_lugar";
            
            //Consulta para llenar combobox con Nombre y Código de los Lugares.
            rs = consulta.hacerConsulta(consultaLugarSQL);
            while(rs.next()){
                ventanaAsociarLugarTour.getVerLugares().addItem(rs.getString("nombre_lugar") + " - " + rs.getString("código_lugar"));
            }
            
            String consultaTourSQL = "SELECT código_tour, nombre_repres "
                    + "FROM Tour "
                    + "ORDER BY código_tour";
            
            //Consulta para llenar combobox con Nombre y Código de los Tours.
            rs = consulta.hacerConsulta(consultaTourSQL);
            while(rs.next()){
                ventanaAsociarLugarTour.getVerTours().addItem(rs.getString("nombre_repres") + ", con ID Tour: " + rs.getString("código_tour"));
            }
            
            ventanaAsociarLugarTour.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Intranet.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_asociarLugarActionPerformed

    private void agregarCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarCiudadActionPerformed
        try {
            VentanaAgregarCiudad ventanaAgregarCiudad = new VentanaAgregarCiudad();
            ventanaAgregarCiudad.setModificacion(modificacion);
            
            String consultaRegionSQL = "SELECT nombre_región, cod_región "
                    + "FROM Región "
                    + "ORDER BY cod_región";
            
            //Consulta para llenar combobox con Nombre y Código de los Lugares.
            rs = consulta.hacerConsulta(consultaRegionSQL);
            while(rs.next()){
                ventanaAgregarCiudad.getVerRegiones().addItem(rs.getString("nombre_región") + " - " + rs.getString("cod_región"));
            }
            
            ventanaAgregarCiudad.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Intranet.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_agregarCiudadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAgregarTour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAgregarTour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAgregarTour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAgregarTour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new VentanaAgregarTour().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton agregarCiudad;
    private javax.swing.JButton agregarTour;
    private javax.swing.JToggleButton asociarLugar;
    private javax.swing.JTextField costoGrupal;
    private javax.swing.JTextField costoIndiv;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField minimoGrupal;
    private javax.swing.JTextField nombreTour;
    private javax.swing.JComboBox<String> verCiudades;
    // End of variables declaration//GEN-END:variables
}
