/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Clases.Consultas;
import Clases.Modificaciones;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author Javier
 */
public class VentanaEliminarVehiculosDeTours extends javax.swing.JFrame {
    public Modificaciones modificacion;
    public Consultas consulta;
    public ResultSet rs;
    
    public void setModificacion(Modificaciones modificacion) {
        this.modificacion = modificacion;
    }
    public void setConsulta(Consultas consulta) {
        this.consulta = consulta;
    }
    public JComboBox<String> getVerTours() {
        return verTours;
    }
    public JComboBox<String> getVerVehiculos() {
        return verVehiculos;
    }
    /**
     * Creates new form VentanaEliminarVehiculosDeTours
     */
    public VentanaEliminarVehiculosDeTours() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        tituloElegirTour = new javax.swing.JLabel();
        textoEliminarVehiculo = new javax.swing.JLabel();
        seleccionarTour = new javax.swing.JToggleButton();
        verTours = new javax.swing.JComboBox<>();
        eliminarVehiculoTour = new javax.swing.JToggleButton();
        verVehiculos = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel4.setText("Eliminar Vehículo de un Tour");

        tituloElegirTour.setText("Por favor, seleccione el Tour:");

        textoEliminarVehiculo.setText("Elija el Vehículo a eliminar del Tour:");
        textoEliminarVehiculo.setVisible(false);

        seleccionarTour.setText("Seleccionar");
        seleccionarTour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccionarTourActionPerformed(evt);
            }
        });

        eliminarVehiculoTour.setText("Eliminar Vehículo del Tour");
        eliminarVehiculoTour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarVehiculoTourActionPerformed(evt);
            }
        });
        eliminarVehiculoTour.setVisible(false);

        verVehiculos.setVisible(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(eliminarVehiculoTour)
                    .addComponent(seleccionarTour)
                    .addComponent(tituloElegirTour)
                    .addComponent(textoEliminarVehiculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(verVehiculos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(verTours, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel4)
                .addGap(30, 30, 30)
                .addComponent(tituloElegirTour)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(verTours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(seleccionarTour)
                .addGap(43, 43, 43)
                .addComponent(textoEliminarVehiculo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(verVehiculos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(eliminarVehiculoTour)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void seleccionarTourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionarTourActionPerformed
        try {
            int n = verTours.getSelectedItem().toString().length();

            String IDt = verTours.getSelectedItem().toString().substring(n-1, n);
            if(Character.isDigit(verTours.getSelectedItem().toString().charAt(n-2))){
                IDt = verTours.getSelectedItem().toString().substring(n-2, n);
            }

            //Consulta para llenar combobox con patente del Vehículo.
            String consultaRequierenSQL = "SELECT R.patente "
            + "FROM Vehículo V, Requieren R, Tour T "
            + "WHERE V.patente = R.patente AND T.código_tour = R.código_tour AND R.código_tour = " + IDt;

            rs = consulta.hacerConsulta(consultaRequierenSQL);
            while(rs.next()){
                getVerVehiculos().addItem(rs.getString("patente"));
            }

            if(getVerVehiculos().getItemCount() == 0){
                JOptionPane.showMessageDialog(null, "No hay Turistas en el Tour especificado.");
                this.setVisible(false);
            }

            tituloElegirTour.setText(verTours.getSelectedItem().toString());
            verTours.setVisible(false);
            seleccionarTour.setVisible(false);
            eliminarVehiculoTour.setVisible(true);
            textoEliminarVehiculo.setVisible(true);
            verVehiculos.setVisible(true);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error al agregar." + ex.getMessage());
        }
    }//GEN-LAST:event_seleccionarTourActionPerformed

    private void eliminarVehiculoTourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarVehiculoTourActionPerformed
        //seleccionar RUT desde el combobox (RUT al final)
        String patente = verVehiculos.getSelectedItem().toString();

        String updateSQL = "DELETE FROM Requieren "
        + "WHERE patente = '"+ patente +"'";

        modificacion.hacerModificacion(updateSQL);
        this.setVisible(false);
    }//GEN-LAST:event_eliminarVehiculoTourActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaEliminarVehiculosDeTours.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaEliminarVehiculosDeTours.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaEliminarVehiculosDeTours.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaEliminarVehiculosDeTours.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaEliminarVehiculosDeTours().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton eliminarVehiculoTour;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JToggleButton seleccionarTour;
    private javax.swing.JLabel textoEliminarVehiculo;
    private javax.swing.JLabel tituloElegirTour;
    private javax.swing.JComboBox<String> verTours;
    private javax.swing.JComboBox<String> verVehiculos;
    // End of variables declaration//GEN-END:variables
}
