/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Clases.Consultas;
import Clases.Modificaciones;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author Javier
 */
public class VentanaEliminarTuristas extends javax.swing.JFrame {
    public Modificaciones modificacion;
    public Consultas consulta;
    public String updateSQL;
    public ResultSet rs;
    
    public void setModificacion(Modificaciones modificacion) {
        this.modificacion = modificacion;
    }

    public void setConsulta(Consultas consulta) {
        this.consulta = consulta;
    }
    
    public JComboBox<String> getVerTuristas() {
        return verTuristas;
    }
    /**
     * Creates new form VentanaEliminarTuristas
     */
    public VentanaEliminarTuristas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        verTuristas = new javax.swing.JComboBox<>();
        eliminarTurista = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        usuarioTexto = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        eliminarEnfermedadesTuristas = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel6.setText("Por favor, seleccione el Turista a eliminar:");

        eliminarTurista.setText("Eliminar Turista");
        eliminarTurista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarTuristaActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel4.setText("Menú para eliminar un Turista existente");

        usuarioTexto.setText("Si el Guía a eliminar está vinculado con algún Tour, no podrá eliminarlo.");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setText("Para eliminar Enfermedades de un Turista, aquí:");

        eliminarEnfermedadesTuristas.setText("Eliminar Enfermedades de un Turista");
        eliminarEnfermedadesTuristas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarEnfermedadesTuristasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(usuarioTexto))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eliminarEnfermedadesTuristas))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addComponent(eliminarTurista))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(verTuristas, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(47, 47, 47)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(verTuristas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(eliminarTurista)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(eliminarEnfermedadesTuristas))
                .addGap(30, 30, 30)
                .addComponent(usuarioTexto)
                .addGap(6, 6, 6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eliminarTuristaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarTuristaActionPerformed
        int n = verTuristas.getSelectedItem().toString().length();
        //seleccionar RUT desde el combobox (RUT al final)
        String RUT = verTuristas.getSelectedItem().toString().substring(n-11, n);
        if(Character.isDigit(verTuristas.getSelectedItem().toString().charAt(n-12))){
            RUT = verTuristas.getSelectedItem().toString().substring(n-12, n);
        }

        updateSQL = "DELETE FROM Turistas "
        + "WHERE RUT_turista = '"+ RUT +"'";

        modificacion.hacerModificacion(updateSQL);
        this.setVisible(false);
    }//GEN-LAST:event_eliminarTuristaActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_formWindowClosing

    private void eliminarEnfermedadesTuristasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarEnfermedadesTuristasActionPerformed
        try {
            String consultaTuristasSQL = "SELECT nombre_turista, RUT_turista "
                    + "FROM Turistas ";
            
            VentanaEliminarEnfermedadesTuristas ventanaEliminarEnfermedadesTuristas = new VentanaEliminarEnfermedadesTuristas();
            ventanaEliminarEnfermedadesTuristas.setModificacion(modificacion);
            ventanaEliminarEnfermedadesTuristas.setConsulta(consulta);
            
            //Consulta para llenar combobox con Nombre y Código de los Tours.
            rs = consulta.hacerConsulta(consultaTuristasSQL);
            while(rs.next()){
                ventanaEliminarEnfermedadesTuristas.getVerTuristas().addItem(rs.getString("nombre_turista") + " - RUT: " + rs.getString("RUT_turista"));
            }
            
            ventanaEliminarEnfermedadesTuristas.setVisible(true);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error al agregar." + ex.getMessage());
        }
    }//GEN-LAST:event_eliminarEnfermedadesTuristasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaEliminarTuristas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaEliminarTuristas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaEliminarTuristas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaEliminarTuristas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaEliminarTuristas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton eliminarEnfermedadesTuristas;
    private javax.swing.JButton eliminarTurista;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel usuarioTexto;
    private javax.swing.JComboBox<String> verTuristas;
    // End of variables declaration//GEN-END:variables
}
