/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Clases.Consultas;
import Clases.Modificaciones;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author Javier
 */
public class VentanaAgregarGuia extends javax.swing.JFrame {
    public Modificaciones modificacion;
    //Nótese que Modificaciones enlaza con la BD, por lo que no se requiere instancia de clases PostgreSQL ni Connection
    public Consultas consulta;
    
    public ResultSet rs;
    public String updateSQL;

    public void setModificacion(Modificaciones modificacion) {
        this.modificacion = modificacion;
    }

    public void setConsulta(Consultas consulta) {
        this.consulta = consulta;
    }
    public JComboBox<String> getVerCiudades() {
        return verCiudades;
    }
    /**
     * Creates new form VentanaAgregarGuia
     */
    public VentanaAgregarGuia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        agregarGuia = new javax.swing.JButton();
        verCiudades = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nombreGuia = new javax.swing.JTextField();
        RUT = new javax.swing.JTextField();
        numeroCasa = new javax.swing.JTextField();
        calle = new javax.swing.JTextField();
        asociarEspecialidad = new javax.swing.JToggleButton();
        agregarCiudad = new javax.swing.JToggleButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        agregarGuia.setText("Agregar Guía");
        agregarGuia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarGuiaActionPerformed(evt);
            }
        });

        jLabel6.setText("Ciudad:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel4.setText("Menu para agregar un Guía");

        jLabel1.setText("Nombre del Guía:");

        jLabel2.setText("RUT del Guía:");

        jLabel3.setText("Número de casa donde vive:");

        jLabel5.setText("Calle donde vive:");

        asociarEspecialidad.setText("Asociar Especialidad a Guía");
        asociarEspecialidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asociarEspecialidadActionPerformed(evt);
            }
        });

        agregarCiudad.setText("Agregar nueva Ciudad");
        agregarCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarCiudadActionPerformed(evt);
            }
        });

        jLabel7.setText("Si desea asociar una Especialidad a un Guía, click en el botón:");

        jLabel8.setText("Si no encuentra la ciudad que busca, puede agregarla aquí:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(jLabel4)
                        .addGap(0, 210, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(agregarCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(asociarEspecialidad))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(249, 249, 249)
                .addComponent(agregarGuia)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(calle, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1)
                                .addComponent(jLabel6))
                            .addGap(259, 259, 259)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(nombreGuia, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                                .addComponent(RUT)
                                .addComponent(numeroCasa)
                                .addComponent(verCiudades, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 210, Short.MAX_VALUE)
                .addComponent(agregarGuia)
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(asociarEspecialidad))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agregarCiudad)
                    .addComponent(jLabel8))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(67, 67, 67)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1)
                        .addComponent(nombreGuia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(RUT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(numeroCasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(calle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(verCiudades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6))
                    .addContainerGap(192, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarGuiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarGuiaActionPerformed
        int n = verCiudades.getSelectedItem().toString().length();
        String IDc = verCiudades.getSelectedItem().toString().substring(n-1, n);

        if(Character.isDigit(verCiudades.getSelectedItem().toString().charAt(n-2))){
            IDc = verCiudades.getSelectedItem().toString().substring(n-2, n);
        }

        updateSQL = "INSERT INTO Guía(RUT_guía, nombre_completo, número_casa, calle, cod_ciudad) "
        + "VALUES "
        + "('"
        + RUT.getText()+"', '"
        + nombreGuia.getText() + "', "
        + numeroCasa.getText()+", '"
        + calle.getText()+"', "
        + IDc +")";

        try{
            modificacion.hacerModificacion(updateSQL);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error al agregar.");
        }
    }//GEN-LAST:event_agregarGuiaActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_formWindowClosing

    private void asociarEspecialidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asociarEspecialidadActionPerformed
        try {
            VentanaAsociarEspecialidadGuia ventanaAsociarEspecialidadGuia = new VentanaAsociarEspecialidadGuia();
            ventanaAsociarEspecialidadGuia.setModificacion(modificacion);
            ventanaAsociarEspecialidadGuia.setConsulta(consulta);

            String consultaGuiasSQL = "SELECT nombre_completo, RUT_guía "
            + "FROM Guía ";
            String consultaEspecialidadesSQL = "SELECT cod_especialidad, descrip_esp "
            + "FROM Especialidad "
            + "ORDER BY cod_especialidad";

            //Consulta para llenar combobox con Nombre y Código de los Lugares.
            rs = consulta.hacerConsulta(consultaEspecialidadesSQL);
            while(rs.next()){
                ventanaAsociarEspecialidadGuia.getVerEspecialidades().addItem(rs.getString("descrip_esp") + " - " + rs.getString("cod_especialidad"));
            }

            //Consulta para llenar combobox con Nombre y Código de los Tours.
            rs = consulta.hacerConsulta(consultaGuiasSQL);
            while(rs.next()){
                ventanaAsociarEspecialidadGuia.getVerGuias().addItem(rs.getString("nombre_completo") + " - con RUT: " + rs.getString("RUT_guía"));
            }

            ventanaAsociarEspecialidadGuia.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Intranet.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_asociarEspecialidadActionPerformed

    private void agregarCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarCiudadActionPerformed
        try {
            VentanaAgregarCiudad ventanaAgregarCiudad = new VentanaAgregarCiudad();
            ventanaAgregarCiudad.setModificacion(modificacion);

            String consultaRegionSQL = "SELECT nombre_región, cod_región "
            + "FROM Región "
            + "ORDER BY cod_región";

            //Consulta para llenar combobox con Nombre y Código de los Lugares.
            rs = consulta.hacerConsulta(consultaRegionSQL);
            while(rs.next()){
                ventanaAgregarCiudad.getVerRegiones().addItem(rs.getString("nombre_región") + " - " + rs.getString("cod_región"));
            }

            ventanaAgregarCiudad.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Intranet.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_agregarCiudadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAgregarGuia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAgregarGuia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAgregarGuia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAgregarGuia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaAgregarGuia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField RUT;
    private javax.swing.JToggleButton agregarCiudad;
    private javax.swing.JButton agregarGuia;
    private javax.swing.JToggleButton asociarEspecialidad;
    private javax.swing.JTextField calle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField nombreGuia;
    private javax.swing.JTextField numeroCasa;
    private javax.swing.JComboBox<String> verCiudades;
    // End of variables declaration//GEN-END:variables
}
